baseurl = "http://nekrut.github.io/lab/"
languageCode = "en-us"
metadataformat = "yaml"
title = "Nekrutenko Lab"
theme = "hugo-alabaster-theme"

disqusShortname = ""
googleAnalytics = ""

[params]
	name = "Nekrutenko Lab"
	description = "Геномика and more"

	github_user   = "galaxyproject"
	github_repo   = "hugo-alabaster-theme"
	github_banner = false

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "img/galaxy_logo.png"


	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = "[Nekrutenko Lab 2016](https://github.com/nekrut)"
	show_powered_by = true